unit MainForm;
interface
uses Winapi.Windows, System.SysUtils, System.Classes, System.IOUtils, Vcl.Forms, Vcl.Controls, Vcl.StdCtrls, Vcl.ExtCtrls, Vcl.Dialogs, Vcl.Grids, NFeReader;
type TMainWindow = class(TForm) private FFolder: TEdit; FGrid: TStringGrid; FData: TArray<TNFeData>; procedure Choose(Sender: TObject); procedure Load(Sender: TObject); procedure Export(Sender: TObject); public constructor Create(AOwner: TComponent); override; end;
var MainWindow: TMainWindow;
implementation
constructor TMainWindow.Create(AOwner: TComponent);
var Bar: TPanel; B: TButton;
begin inherited; Caption := 'Descomplicador de NFe'; Width := 1050; Height := 650; Position := poScreenCenter; Bar := TPanel.Create(Self); Bar.Parent := Self; Bar.Align := alTop; Bar.Height := 52; FFolder := TEdit.Create(Self); FFolder.Parent := Bar; FFolder.SetBounds(10, 13, 650, 26); B := TButton.Create(Self); B.Parent := Bar; B.Caption := 'Pasta...'; B.SetBounds(670, 11, 90, 30); B.OnClick := Choose; B := TButton.Create(Self); B.Parent := Bar; B.Caption := 'Ler XMLs'; B.SetBounds(770, 11, 90, 30); B.OnClick := Load; B := TButton.Create(Self); B.Parent := Bar; B.Caption := 'Exportar CSV'; B.SetBounds(870, 11, 110, 30); B.OnClick := Export; FGrid := TStringGrid.Create(Self); FGrid.Parent := Self; FGrid.Align := alClient; FGrid.ColCount := 7; FGrid.FixedRows := 1; FGrid.RowCount := 2; FGrid.Options := FGrid.Options + [goColSizing]; FGrid.Cells[0,0] := 'Arquivo'; FGrid.Cells[1,0] := 'Fornecedor'; FGrid.Cells[2,0] := 'CNPJ'; FGrid.Cells[3,0] := 'Data'; FGrid.Cells[4,0] := 'Número'; FGrid.Cells[5,0] := 'Total'; FGrid.Cells[6,0] := 'Erro'; end;
procedure TMainWindow.Choose(Sender: TObject); var D: TFileOpenDialog; begin D := TFileOpenDialog.Create(nil); try D.Options := [fdoPickFolders]; if D.Execute then FFolder.Text := D.FileName; finally D.Free; end; end;
procedure TMainWindow.Load(Sender: TObject); var Files: TArray<string>; I: Integer; begin if not TDirectory.Exists(FFolder.Text) then begin ShowMessage('Selecione uma pasta válida.'); Exit; end; Files := TDirectory.GetFiles(FFolder.Text, '*.xml'); SetLength(FData, Length(Files)); FGrid.RowCount := Length(Files)+1; for I := 0 to High(Files) do begin FData[I] := ReadNFe(Files[I]); FGrid.Cells[0,I+1] := ExtractFileName(Files[I]); FGrid.Cells[1,I+1] := FData[I].Supplier; FGrid.Cells[2,I+1] := FData[I].CNPJ; FGrid.Cells[3,I+1] := FData[I].DateText; FGrid.Cells[4,I+1] := FData[I].NumberText; FGrid.Cells[5,I+1] := CurrToStr(FData[I].Total); FGrid.Cells[6,I+1] := FData[I].ErrorText; end; end;
procedure TMainWindow.Export(Sender: TObject); var D: TSaveDialog; Lines: TStringList; Item: TNFeData; begin if Length(FData)=0 then Exit; D:=TSaveDialog.Create(nil); Lines:=TStringList.Create; try D.Filter:='CSV|*.csv'; D.FileName:='nfe-relatorio.csv'; if D.Execute then begin Lines.Add('Arquivo;Fornecedor;CNPJ;Data;Numero;Total;Erro'); for Item in FData do Lines.Add(CsvLine(Item)); Lines.SaveToFile(D.FileName, TEncoding.UTF8); ShowMessage('CSV exportado.'); end; finally Lines.Free; D.Free; end; end;
end.
